### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by astroming** [lbn187/DLGNN#2]

**Comment by lbn187** [comment]
hidden_dim=512
----- 原始邮件 -----
发件人：astroming ***@***.***>
收件人：lbn187/DLGNN ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[lbn187/DLGNN] Setting details of baseline GraphSAGE on DDI (#2)
日期：2021年06月07日 11点05分


Hi, your experimental results are promising. I am working on re-producing your result. However, I cannot get the result of the baseline GraphSAGE on DDI, i.e. 79%. Could you please share the setting details on GraphSAGE. Thanks.
